### ISSUE TITLE
yaml header block recongnized as H2 heading instead of metadata.

### ISSUE THREAD

**Issue by seoyoungjin** [huntlabs/hunt-markdown#2]
Many mardown documents contain YAML metadata block like this.

```
---
title: CommonMark Spec
author: John MacFarlane
version: 0.28
date: '2017-08-01'
license: '[CC-BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)'
---
```

hunt-markdown parser recognizes this as h2 heading.
This must be treated as information block and renderer may render or skip this by option.

https://github.com/huntlabs/hunt-markdown/blob/master/example/resources/spec.md

**Comment by zoujiaqing** [comment]
test it at tomorrow, thanks!

**Comment by seoyoungjin** [comment]
> test it at tomorrow, thanks!

I didn't know how to use YamlFrontMatterExtension parser extension.
I'm trying to learn how to do that.
If there are some document about extension, it will be very helpful.

Sorry to bother you.
